# Copyright (C) 2024  ANSSI
# SPDX-License-Identifier: CC0-1.0
services:
  suricata:
    build: ./suricata
    image: anssi/shovel-suricata:dev
    volumes:
      - "./input_pcaps:/input_pcaps:rw"
      - "./suricata/rules:/suricata/rules:ro"
      - "./suricata/output:/suricata/output:rw"

    # Mode B: capture interface (fast, requires root on vulnbox and in Docker)
    # Drastically reduces ingest delay, but requires to setup traffic mirroring
    # between the vulnbox game interface and a team server.
    command: -i tun5
    cap_add:
      - NET_ADMIN
    network_mode: "host"

  frontend:
    build: ./frontend
    restart: always
    volumes:
      - "./input_pcaps:/input_pcaps:ro" # remove to prevent users from downloading pcaps
      - "./suricata/output:/suricata/output:rw"
    ports:
      - 127.0.0.1:3000:3000
    env_file:
      - .env