# Copyright (C) 2024  ANSSI
# SPDX-License-Identifier: CC0-1.0
services:
  suricata:
    build: ./suricata
    image: anssi/shovel-suricata:dev
    volumes:
      - "./input_pcaps:/input_pcaps:ro"
      - "./suricata/rules:/suricata/rules:ro"
      - "./suricata/output:/suricata/output:rw"

    # Mode C: PCAP-over-IP (fast, requires root on vulnbox)
    # Connects to a PCAP-over-IP server, such as pcap-broker to read PCAP data.
    command: -r /dev/stdin
    restart: always
    depends_on:
      - pcap-broker
    environment:
      - PCAP_OVER_IP=pcap-broker:4242

  webapp:
    build: ./webapp
    image: anssi/shovel-webapp:dev
    restart: always
    volumes:
      - "./input_pcaps:/input_pcaps:ro" # remove to prevent users from downloading pcaps
      - "./suricata/output:/suricata/output:rw"
      - "./services_config.json:/webapp/services_config.json:rw"
    ports:
      - 0.0.0.0:8000:8000
    env_file:
      - .env

  pcap-broker:
    container_name: pcap-broker-op
    build:
      context: .
      dockerfile_inline: |
        FROM golang:alpine
        RUN apk add --no-cache build-base libpcap-dev openssh-client tcpdump
        RUN go install github.com/fox-it/pcap-broker@latest
        ENTRYPOINT ["pcap-broker"]
    restart: always
    volumes:
      - "~/.ssh/id_ed25519:/root/.ssh/id_ed25519:ro"
    environment:
      PCAP_COMMAND: |-
        ssh root@10.60.1.1 -oStrictHostKeyChecking=no
        tcpdump -U --immediate-mode -ni game -s 65535 -w - not tcp port 22
      LISTEN_ADDRESS: 0.0.0.0:4242
